# Generated by Django 5.0.2 on 2024-03-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
