# Generated by Django 5.0.2 on 2024-03-15 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="delivery",
        ),
        migrations.RemoveField(
            model_name="post",
            name="services",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="postType",
            new_name="type",
        ),
        migrations.RemoveField(
            model_name="post",
            name="link",
        ),
        migrations.DeleteModel(
            name="Delivery",
        ),
        migrations.AddField(
            model_name="post",
            name="delivery",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.AddField(
            model_name="post",
            name="services",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
