# Generated by Django 5.0.2 on 2024-03-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0002_remove_post_delivery_remove_post_services_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="person",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
