# Generated by Django 5.0.2 on 2024-03-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0003_post_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="link",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
