# Generated by Django 5.0.2 on 2024-03-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0004_post_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
