# Generated by Django 5.0.2 on 2024-03-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0005_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_link",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
