# Generated by Django 5.0.2 on 2024-03-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0006_post_image_link_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
