# Generated by Django 5.0.2 on 2024-03-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0007_post_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image_link",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.URLField(null=True),
        ),
    ]
