# Generated by Django 5.0.2 on 2024-03-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet", "0008_remove_post_image_link_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="delivery",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="services",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
